### ISSUE TITLE
Percentages have many many decimal places

### ISSUE THREAD

**Issue by huonw** [rust-lang-nursery/rustc-pr-tracking#2]
In the "Show percentages instead of absolute numbers" mode, the percentages have many more decimal places than necessary. I imagine for this that rounding to 0, 1 or 2 decimal places would be fine.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/1203825/50765349-c38c7780-12c9-11e9-99c1-d8f13f955ec4.png">

**Comment by pietroalbini** [comment]
Thanks! Fixed.
