### ISSUE TITLE
no longer updating

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rustc-pr-tracking#3]
there are no updates since 2019-01-08: https://rust-lang-nursery.github.io/rustc-pr-tracking/

>Do not run the ci.sh script: it's meant to be run by Travis, and it will push new commits to this repository.

Perhaps this is more travis-ci.org->.com migration fallout?

**Comment by pietroalbini** [comment]
Thanks for pointing this out! I'll contact Travis support soon.
